"""init

Revision ID: 8d30a0731ba0
Revises:
Create Date: 2026-01-20 13:07:36.736169

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8d30a0731ba0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
