"""auto

Revision ID: d5825fe9e5af
Revises: eec23e5109cc
Create Date: 2026-01-22 00:01:32.326136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5825fe9e5af"
down_revision: Union[str, None] = "eec23e5109cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=True))
    op.drop_column("users", "id_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("id_admin", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
