"""auto

Revision ID: eec23e5109cc
Revises: 8d30a0731ba0
Create Date: 2026-01-20 13:42:36.490237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eec23e5109cc"
down_revision: Union[str, None] = "8d30a0731ba0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("heartbeat", sa.Column("label", sa.String(), nullable=True))
    op.create_index(op.f("ix_heartbeat_label"), "heartbeat", ["label"], unique=False)
    op.add_column("statuses", sa.Column("label", sa.String(), nullable=True))
    op.create_index(op.f("ix_statuses_label"), "statuses", ["label"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_statuses_label"), table_name="statuses")
    op.drop_column("statuses", "label")
    op.drop_index(op.f("ix_heartbeat_label"), table_name="heartbeat")
    op.drop_column("heartbeat", "label")
    # ### end Alembic commands ###
